#!/usr/bin/env python3
from RPi import GPIO
from time import sleep
from sys import argv

PIN = 26
DIT = 0.00010 # s
DAH = 3 * DIT
SIGNAL_SPACE = DIT
LETTER_SPACE = 3 * DIT - SIGNAL_SPACE
WORD_SPACE = 7 * DIT - LETTER_SPACE

morse = {"a": ".-", "b": "-...", "c": "-.-.", "d": "-..", "e": ".", "f": "..-.", "g": "--.", "h": "....", "i": "..", "j": ".---", "k": "-.-", "l": ".-..", "m": "--", "n": "-.", "o": "---", "p": ".--.", "q": "--.-", "r": ".-.", "s": "...", "t": "-", "u": "..-", "v": "...-", "w": ".--", "x": "-..-", "y": "-.--", "z": "--..", "0": "-----", "1": ".----", "2": "..---", "3": "...--", "4": "....-", "5": ".....", "6": "-....", "7": "--...", "8": "---..", "9": "----.", ".": ".-.-.-", ",": "--..--", "?": "..--..", "'": ".----.", "!": "-.-.--", "/": "-..-.", "(": "-.--.", ")": "-.--.-", "&": ".-...", ":": "---...", ";": "-.-.-.", "=": "-...-", "+": ".-.-.", "-": "-....-", "_": "..--.-", "\"": ".-..-.", "$": "...-..-", "@": ".--.-.", "¿": "..-.-", "¡": "--...-"}

"""
def sleep(duration):
	end = perf_counter() + duration
	while perf_counter() < end: pass
"""

def send_char(char):
	if char == " ":
		sleep(WORD_SPACE)
		return

	seq = morse.get(char)
	if not seq:
		print(f"Invalid: '{char}'")
		return

	for signal in seq:
		GPIO.output(PIN, True)
		sleep(DIT if signal == "." else DAH)
		GPIO.output(PIN, False)
		sleep(SIGNAL_SPACE)
	sleep(LETTER_SPACE)

if __name__ == "__main__":
	if len(argv) <= 1:
		print("ERROR: Nothing to send")
		sys.exit(1)
	else:
		args = argv[1:]
		text = " ".join(args[1:])
		if args[0].isdecimal():
			send_quantity = int(args[0])
		else:
			send_quantity = 1
			text = args[0] + " " + text
	text = text.lower()

	GPIO.setmode(GPIO.BCM)
	GPIO.setup(PIN, GPIO.OUT)

	try:
		for i in range(send_quantity):
			for c in text:
				send_char(c)
			if i != send_quantity - 1:
				sleep(WORD_SPACE * 3)
	finally:
		GPIO.cleanup()
